site: Bitsoffreedom

url:
baseurl: /

collections:
  pages:
    output: true
    permalink: /:name
  highlights:
    output: true
    permalink: /highlight/:slug
  plans:
    output: true
    permalink: /plan/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "highlights"
    values:
      layout: "highlights"
  -
    scope:
      path: ""
      type: "plans"
    values:
      layout: "plans"

markdown: kramdown
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-polyglot


languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true